# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['starter.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.ini', '.'),
        ('coordenadas.json', '.'),
        ('README.md', '.'),
        ('sistema_principal.py', '.'),
        ('automacao.py', '.'),
        ('monitor_mt5.py', '.'),
        ('backtest_core.py', '.'),
        ('calibrar.py', '.'),
        ('verificar_config.py', '.'),
        ('extracao_oos.py', '.'),
    ],
    hiddenimports=[
        'sistema_principal',
        'automacao',
        'monitor_mt5',
        'backtest_core',
        'calibrar',
        'verificar_config',
        'extracao_oos',
        'pyautogui',
        'psutil',
        'pyperclip',
        'configparser',
        'pathlib',
        'json',
        'subprocess',
        'time',
        'socket',
        're',
        'dataclasses',
        'logging',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MT5_Ninja_Backtester',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    version='version_info.txt',
)
